/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_qsys_0' in SOPC Builder design 'nios_system'
 * SOPC Builder design path: ../../nios_system.sopcinfo
 *
 * Generated: Fri Dec 13 14:52:44 EST 2019
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08001020
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 65536
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 65536
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_qsys_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08001020
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 65536
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 65536
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Custom instruction macros
 *
 */

#define ALT_CI_FLOATING_POINT_ADDER_0(A,B) __builtin_custom_inii(ALT_CI_FLOATING_POINT_ADDER_0_N,(A),(B))
#define ALT_CI_FLOATING_POINT_ADDER_0_N 0x0
#define ALT_CI_FLOATING_POINT_MULTIPLIER_0(A,B) __builtin_custom_inii(ALT_CI_FLOATING_POINT_MULTIPLIER_0_N,(A),(B))
#define ALT_CI_FLOATING_POINT_MULTIPLIER_0_N 0x1


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_PERFORMANCE_COUNTER
#define __ALTERA_AVALON_TIMER
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_QSYS
#define __ALTERA_UP_AVALON_SRAM
#define __ALTERA_UP_AVALON_VIDEO_CHARACTER_BUFFER_WITH_DMA
#define __ALTERA_UP_AVALON_VIDEO_PIXEL_BUFFER_DMA
#define __FLOATING_POINT_ADDER
#define __FLOATING_POINT_MULTIPLIER
#define __NN_ACC_SINGLE_BUFFER_VERSION


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x80004f0
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x80004f0
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x80004f0
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_system"


/*
 * altera_ro_zipfs configuration
 *
 */

#define ALTERA_RO_ZIPFS_BASE 0x8800000
#define ALTERA_RO_ZIPFS_NAME "/mnt/rozipfs"
#define ALTERA_RO_ZIPFS_OFFSET 0x0


/*
 * dma_0 configuration
 *
 */

#define ALT_MODULE_CLASS_dma_0 altera_avalon_dma
#define DMA_0_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_0_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_HW_TRANSACTIONS 0
#define DMA_0_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_WORD_TRANSACTIONS 1
#define DMA_0_BASE 0x80004c0
#define DMA_0_IRQ 2
#define DMA_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_0_LENGTHWIDTH 12
#define DMA_0_MAX_BURST_SIZE 1024
#define DMA_0_NAME "/dev/dma_0"
#define DMA_0_SPAN 32
#define DMA_0_TYPE "altera_avalon_dma"


/*
 * generic_tristate_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_generic_tristate_controller_0 altera_generic_tristate_controller
#define GENERIC_TRISTATE_CONTROLLER_0_BASE 0x8800000
#define GENERIC_TRISTATE_CONTROLLER_0_HOLD_VALUE 60
#define GENERIC_TRISTATE_CONTROLLER_0_IRQ -1
#define GENERIC_TRISTATE_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GENERIC_TRISTATE_CONTROLLER_0_NAME "/dev/generic_tristate_controller_0"
#define GENERIC_TRISTATE_CONTROLLER_0_SETUP_VALUE 60
#define GENERIC_TRISTATE_CONTROLLER_0_SIZE 8388608u
#define GENERIC_TRISTATE_CONTROLLER_0_SPAN 8388608
#define GENERIC_TRISTATE_CONTROLLER_0_TIMING_UNITS "ns"
#define GENERIC_TRISTATE_CONTROLLER_0_TYPE "altera_generic_tristate_controller"
#define GENERIC_TRISTATE_CONTROLLER_0_WAIT_VALUE 160


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_0
#define ALT_TIMESTAMP_CLK TIMER_0


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x80004f0
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * new_sdram_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_new_sdram_controller_0 altera_avalon_new_sdram_controller
#define NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define NEW_SDRAM_CONTROLLER_0_IRQ -1
#define NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 32
#define NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 1
#define NEW_SDRAM_CONTROLLER_0_SPAN 134217728
#define NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define NEW_SDRAM_CONTROLLER_0_T_AC 5.5
#define NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define NEW_SDRAM_CONTROLLER_0_T_RCD 20.0
#define NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define NEW_SDRAM_CONTROLLER_0_T_RP 20.0
#define NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * new_sdram_controller_0 configuration as viewed by dma_0_read_master
 *
 */

#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ -1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 32
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SPAN 134217728
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_AC 5.5
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RCD 20.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RP 20.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * new_sdram_controller_0 configuration as viewed by dma_0_write_master
 *
 */

#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ -1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 32
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SPAN 134217728
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_AC 5.5
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RCD 20.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RP 20.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * nn_acc_single_buffer_version_1 configuration
 *
 */

#define ALT_MODULE_CLASS_nn_acc_single_buffer_version_1 nn_acc_single_buffer_version
#define NN_ACC_SINGLE_BUFFER_VERSION_1_BASE 0x8000000
#define NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ -1
#define NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NN_ACC_SINGLE_BUFFER_VERSION_1_NAME "/dev/nn_acc_single_buffer_version_1"
#define NN_ACC_SINGLE_BUFFER_VERSION_1_SPAN 1024
#define NN_ACC_SINGLE_BUFFER_VERSION_1_TYPE "nn_acc_single_buffer_version"


/*
 * nn_acc_single_buffer_version_1 configuration as viewed by dma_0_read_master
 *
 */

#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_BASE 0x8000000
#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ -1
#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_NAME "/dev/nn_acc_single_buffer_version_1"
#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_SPAN 1024
#define DMA_0_READ_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_TYPE "nn_acc_single_buffer_version"


/*
 * nn_acc_single_buffer_version_1 configuration as viewed by dma_0_write_master
 *
 */

#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_BASE 0x8000000
#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ -1
#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_NAME "/dev/nn_acc_single_buffer_version_1"
#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_SPAN 1024
#define DMA_0_WRITE_MASTER_NN_ACC_SINGLE_BUFFER_VERSION_1_TYPE "nn_acc_single_buffer_version"


/*
 * performance_counter_0 configuration
 *
 */

#define ALT_MODULE_CLASS_performance_counter_0 altera_avalon_performance_counter
#define PERFORMANCE_COUNTER_0_BASE 0x8000400
#define PERFORMANCE_COUNTER_0_HOW_MANY_SECTIONS 7
#define PERFORMANCE_COUNTER_0_IRQ -1
#define PERFORMANCE_COUNTER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERFORMANCE_COUNTER_0_NAME "/dev/performance_counter_0"
#define PERFORMANCE_COUNTER_0_SPAN 128
#define PERFORMANCE_COUNTER_0_TYPE "altera_avalon_performance_counter"


/*
 * sram_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sram_0 altera_up_avalon_sram
#define SRAM_0_BASE 0x8200000
#define SRAM_0_IRQ -1
#define SRAM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_0_NAME "/dev/sram_0"
#define SRAM_0_SPAN 2097152
#define SRAM_0_TYPE "altera_up_avalon_sram"


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x80004a0
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_IRQ 1
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 499999999
#define TIMER_0_MULT 1.0
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 10
#define TIMER_0_PERIOD_UNITS "s"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 0
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 0
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * video_character_buffer_with_dma_0_avalon_char_buffer_slave configuration
 *
 */

#define ALT_MODULE_CLASS_video_character_buffer_with_dma_0_avalon_char_buffer_slave altera_up_avalon_video_character_buffer_with_dma
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_BASE 0x8002000
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_IRQ -1
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_NAME "/dev/video_character_buffer_with_dma_0_avalon_char_buffer_slave"
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_SPAN 8192
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_TYPE "altera_up_avalon_video_character_buffer_with_dma"


/*
 * video_character_buffer_with_dma_0_avalon_char_control_slave configuration
 *
 */

#define ALT_MODULE_CLASS_video_character_buffer_with_dma_0_avalon_char_control_slave altera_up_avalon_video_character_buffer_with_dma
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_BASE 0x80004f8
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_IRQ -1
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_NAME "/dev/video_character_buffer_with_dma_0_avalon_char_control_slave"
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_SPAN 8
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_TYPE "altera_up_avalon_video_character_buffer_with_dma"


/*
 * video_pixel_buffer_dma_0 configuration
 *
 */

#define ALT_MODULE_CLASS_video_pixel_buffer_dma_0 altera_up_avalon_video_pixel_buffer_dma
#define VIDEO_PIXEL_BUFFER_DMA_0_BASE 0x80004e0
#define VIDEO_PIXEL_BUFFER_DMA_0_IRQ -1
#define VIDEO_PIXEL_BUFFER_DMA_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIDEO_PIXEL_BUFFER_DMA_0_NAME "/dev/video_pixel_buffer_dma_0"
#define VIDEO_PIXEL_BUFFER_DMA_0_SPAN 16
#define VIDEO_PIXEL_BUFFER_DMA_0_TYPE "altera_up_avalon_video_pixel_buffer_dma"

#endif /* __SYSTEM_H_ */
